// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: forums.sql

package mybb

import (
	"context"
)

const fetchForums = `-- name: FetchForums :many
select fid, name, description
from forums
`

type FetchForumsRow struct {
	Fid         int64
	Name        string
	Description string
}

func (q *Queries) FetchForums(ctx context.Context) ([]FetchForumsRow, error) {
	rows, err := q.db.QueryContext(ctx, fetchForums)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchForumsRow
	for rows.Next() {
		var i FetchForumsRow
		if err := rows.Scan(&i.Fid, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
