// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package mybb

import (
	"database/sql"
)

type Adminlog struct {
	Uid       int64
	Ipaddress string
	Dateline  int64
	Module    string
	Action    string
	Data      string
}

type Adminoption struct {
	Uid                int64
	Cpstyle            string
	Cplanguage         string
	Codepress          int64
	Notes              string
	Permissions        string
	Defaultviews       string
	Loginattempts      int64
	Loginlockoutexpiry int64
	Authsecret         string
	RecoveryCodes      string
}

type Adminsession struct {
	Sid           string
	Uid           int64
	Loginkey      string
	Ip            string
	Dateline      int64
	Lastactive    int64
	Data          string
	Useragent     string
	Authenticated int64
}

type Adminview struct {
	Vid                 int64
	Uid                 int64
	Title               string
	Type                string
	Visibility          int64
	Fields              string
	Conditions          string
	CustomProfileFields string
	Sortby              string
	Sortorder           string
	Perpage             int64
	ViewType            string
}

type Announcement struct {
	Aid          int64
	Fid          int64
	Uid          int64
	Subject      string
	Message      string
	Startdate    int64
	Enddate      int64
	Allowhtml    int64
	Allowmycode  int64
	Allowsmilies int64
}

type Attachment struct {
	Aid          int64
	Pid          int64
	Posthash     string
	Uid          int64
	Filename     sql.NullString
	Filetype     string
	Filesize     int64
	Attachname   sql.NullString
	Downloads    int64
	Dateuploaded int64
	Visible      int64
	Thumbnail    string
}

type Attachtype struct {
	Atid          int64
	Name          string
	Mimetype      string
	Extension     string
	Maxsize       int64
	Icon          string
	Enabled       int64
	Forcedownload int64
	Groups        string
	Forums        string
	Avatarfile    int64
}

type Awaitingactivation struct {
	Aid       int64
	Uid       int64
	Dateline  int64
	Code      string
	Type      string
	Validated int64
	Misc      string
}

type Badword struct {
	Bid         int64
	Badword     string
	Replacement string
	Regex       int64
}

type Bam struct {
	Pid          int64
	Announcement string
	Class        string
	Link         sql.NullString
	Active       int64
	Disporder    int64
	Groups       sql.NullString
	Text         int64
	Pinned       int64
}

type Banfilter struct {
	Fid      int64
	Filter   string
	Type     int64
	Lastuse  int64
	Dateline int64
}

type Banned struct {
	Uid                 int64
	Gid                 int64
	Oldgroup            int64
	Oldadditionalgroups string
	Olddisplaygroup     int64
	Admin               int64
	Dateline            int64
	Bantime             string
	Lifted              int64
	Reason              string
}

type Buddyrequest struct {
	ID    int64
	Uid   int64
	Touid int64
	Text  int64
}

type Calendar struct {
	Cid            int64
	Name           string
	Disporder      int64
	Startofweek    int64
	Showbirthdays  int64
	Eventlimit     int64
	Moderation     int64
	Allowhtml      int64
	Allowmycode    int64
	Allowimgcode   int64
	Allowvideocode int64
	Allowsmilies   int64
}

type Calendarpermission struct {
	Cid               int64
	Gid               int64
	Canviewcalendar   int64
	Canaddevents      int64
	Canbypasseventmod int64
	Canmoderateevents int64
}

type Captcha struct {
	Imagehash   string
	Imagestring string
	Dateline    int64
	Used        int64
}

type Datacache struct {
	Title string
	Cache string
}

type Delayedmoderation struct {
	Did           int64
	Type          string
	Delaydateline int64
	Uid           int64
	Fid           int64
	Tids          string
	Dateline      int64
	Inputs        string
}

type Event struct {
	Eid            int64
	Cid            int64
	Uid            int64
	Name           string
	Description    string
	Visible        int64
	Private        int64
	Dateline       int64
	Starttime      int64
	Endtime        int64
	Timezone       string
	Ignoretimezone int64
	Usingtime      int64
	Repeats        string
}

type Forum struct {
	Fid               int64
	Name              string
	Description       string
	Linkto            string
	Type              string
	Pid               int64
	Parentlist        string
	Disporder         int64
	Active            int64
	Open              int64
	Threads           int64
	Posts             int64
	Lastpost          int64
	Lastposter        string
	Lastposteruid     int64
	Lastposttid       int64
	Lastpostsubject   string
	Allowhtml         int64
	Allowmycode       int64
	Allowsmilies      int64
	Allowimgcode      int64
	Allowvideocode    int64
	Allowpicons       int64
	Allowtratings     int64
	Usepostcounts     int64
	Usethreadcounts   int64
	Requireprefix     int64
	Password          string
	Showinjump        int64
	Style             int64
	Overridestyle     int64
	Rulestype         int64
	Rulestitle        string
	Rules             string
	Unapprovedthreads int64
	Unapprovedposts   int64
	Deletedthreads    int64
	Deletedposts      int64
	Defaultdatecut    int64
	Defaultsortby     string
	Defaultsortorder  string
}

type Forumpermission struct {
	Pid                    int64
	Fid                    int64
	Gid                    int64
	Canview                int64
	Canviewthreads         int64
	Canonlyviewownthreads  int64
	Candlattachments       int64
	Canpostthreads         int64
	Canpostreplys          int64
	Canonlyreplyownthreads int64
	Canpostattachments     int64
	Canratethreads         int64
	Caneditposts           int64
	Candeleteposts         int64
	Candeletethreads       int64
	Caneditattachments     int64
	Canviewdeletionnotice  int64
	Modposts               int64
	Modthreads             int64
	ModEditPosts           int64
	Modattachments         int64
	Canpostpolls           int64
	Canvotepolls           int64
	Cansearch              int64
}

type Forumsread struct {
	Fid      int64
	Uid      int64
	Dateline int64
}

type Forumsubscription struct {
	Fsid int64
	Fid  int64
	Uid  int64
}

type Groupleader struct {
	Lid               int64
	Gid               int64
	Uid               int64
	Canmanagemembers  int64
	Canmanagerequests int64
	Caninvitemembers  int64
}

type Helpdoc struct {
	Hid            int64
	Sid            int64
	Name           string
	Description    string
	Document       string
	Usetranslation int64
	Enabled        int64
	Disporder      int64
}

type Helpsection struct {
	Sid            int64
	Name           string
	Description    string
	Usetranslation int64
	Enabled        int64
	Disporder      int64
}

type Icon struct {
	Iid  int64
	Name string
	Path string
}

type Joinrequest struct {
	Rid      int64
	Uid      int64
	Gid      int64
	Reason   string
	Dateline int64
	Invite   int64
}

type Mailerror struct {
	Eid         int64
	Subject     string
	Message     string
	Toaddress   string
	Fromaddress string
	Dateline    int64
	Error       string
	Smtperror   string
	Smtpcode    int64
}

type Maillog struct {
	Mid       int64
	Subject   string
	Message   string
	Dateline  int64
	Fromuid   int64
	Fromemail string
	Touid     int64
	Toemail   string
	Tid       int64
	Ipaddress string
	Type      int64
}

type Mailqueue struct {
	Mid      int64
	Mailto   string
	Mailfrom string
	Subject  string
	Message  string
	Headers  string
}

type Massemail struct {
	Mid         int64
	Uid         int64
	Subject     string
	Message     string
	Htmlmessage string
	Type        int64
	Format      int64
	Dateline    int64
	Senddate    int64
	Status      int64
	Sentcount   int64
	Totalcount  int64
	Conditions  string
	Perpage     int64
}

type Moderator struct {
	Mid                        int64
	Fid                        int64
	ID                         int64
	Isgroup                    int64
	Caneditposts               int64
	Cansoftdeleteposts         int64
	Canrestoreposts            int64
	Candeleteposts             int64
	Cansoftdeletethreads       int64
	Canrestorethreads          int64
	Candeletethreads           int64
	Canviewips                 int64
	Canviewunapprove           int64
	Canviewdeleted             int64
	Canopenclosethreads        int64
	Canstickunstickthreads     int64
	Canapproveunapprovethreads int64
	Canapproveunapproveposts   int64
	Canapproveunapproveattachs int64
	Canmanagethreads           int64
	Canmanagepolls             int64
	Canpostclosedthreads       int64
	Canmovetononmodforum       int64
	Canusecustomtools          int64
	Canmanageannouncements     int64
	Canmanagereportedposts     int64
	Canviewmodlog              int64
}

type Moderatorlog struct {
	Uid       int64
	Dateline  int64
	Fid       int64
	Tid       int64
	Pid       int64
	Action    string
	Data      string
	Ipaddress string
}

type Modtool struct {
	Tid           int64
	Name          string
	Description   string
	Forums        string
	Groups        string
	Type          string
	Postoptions   string
	Threadoptions string
}

type Mycode struct {
	Cid         int64
	Title       string
	Description string
	Regex       string
	Replacement string
	Active      int64
	Parseorder  int64
}

type Poll struct {
	Pid        int64
	Tid        int64
	Question   string
	Dateline   int64
	Options    string
	Votes      string
	Numoptions int64
	Numvotes   int64
	Timeout    int64
	Closed     int64
	Multiple   int64
	Public     int64
	Maxoptions int64
}

type Pollvote struct {
	Vid        int64
	Pid        int64
	Uid        int64
	Voteoption int64
	Dateline   int64
	Ipaddress  string
}

type Post struct {
	Pid        int64
	Tid        int64
	Replyto    int64
	Fid        int64
	Subject    string
	Icon       int64
	Uid        int64
	Username   string
	Dateline   int64
	Message    string
	Ipaddress  string
	Includesig int64
	Smilieoff  int64
	Edituid    int64
	Edittime   int64
	Editreason string
	Visible    int64
}

type Privatemessage struct {
	Pmid       int64
	Uid        int64
	Toid       int64
	Fromid     int64
	Recipients string
	Folder     int64
	Subject    string
	Icon       int64
	Message    string
	Dateline   int64
	Deletetime int64
	Status     int64
	Statustime int64
	Includesig int64
	Smilieoff  int64
	Receipt    int64
	Readtime   int64
	Ipaddress  string
}

type Profilefield struct {
	Fid            int64
	Name           string
	Description    string
	Disporder      int64
	Type           string
	Regex          string
	Length         int64
	Maxlength      int64
	Required       int64
	Registration   int64
	Profile        int64
	Postbit        int64
	Viewableby     string
	Editableby     string
	Postnum        int64
	Allowhtml      int64
	Allowmycode    int64
	Allowsmilies   int64
	Allowimgcode   int64
	Allowvideocode int64
}

type Promotion struct {
	Pid               int64
	Title             string
	Description       string
	Enabled           int64
	Logging           int64
	Posts             int64
	Posttype          string
	Threads           int64
	Threadtype        string
	Registered        int64
	Registeredtype    string
	Online            int64
	Onlinetype        string
	Reputations       int64
	Reputationtype    string
	Referrals         int64
	Referralstype     string
	Warnings          int64
	Warningstype      string
	Requirements      string
	Originalusergroup string
	Newusergroup      int64
	Usergrouptype     string
}

type Promotionlog struct {
	Plid         int64
	Pid          int64
	Uid          int64
	Oldusergroup string
	Newusergroup int64
	Dateline     int64
	Type         string
}

type Question struct {
	Qid       int64
	Question  string
	Answer    string
	Shown     int64
	Correct   int64
	Incorrect int64
	Active    int64
}

type Questionsession struct {
	Sid      string
	Qid      int64
	Dateline int64
}

type Reportedcontent struct {
	Rid          int64
	ID           int64
	Id2          int64
	Id3          int64
	Uid          int64
	Reportstatus int64
	Reasonid     int64
	Reason       string
	Type         string
	Reports      int64
	Reporters    string
	Dateline     int64
	Lastreport   int64
}

type Reportreason struct {
	Rid       int64
	Title     string
	Appliesto string
	Extra     int64
	Disporder int64
}

type Reputation struct {
	Rid        int64
	Uid        int64
	Adduid     int64
	Pid        int64
	Reputation int64
	Dateline   int64
	Comments   string
}

type Searchlog struct {
	Sid        string
	Uid        int64
	Dateline   int64
	Ipaddress  string
	Threads    string
	Posts      string
	Resulttype string
	Querycache string
	Keywords   string
}

type Session struct {
	Sid          string
	Uid          int64
	Ip           string
	Time         int64
	Location     string
	Useragent    string
	Anonymous    int64
	Nopermission int64
	Location1    int64
	Location2    int64
}

type Setting struct {
	Sid         int64
	Name        string
	Title       string
	Description string
	Optionscode string
	Value       string
	Disporder   int64
	Gid         int64
	Isdefault   int64
}

type Settinggroup struct {
	Gid         int64
	Name        string
	Title       string
	Description string
	Disporder   int64
	Isdefault   int64
}

type Smily struct {
	Sid           int64
	Name          string
	Find          string
	Image         string
	Disporder     int64
	Showclickable int64
}

type Spamlog struct {
	Sid       int64
	Username  string
	Email     string
	Ipaddress string
	Dateline  int64
	Data      string
}

type Spider struct {
	Sid       int64
	Name      string
	Theme     int64
	Language  string
	Usergroup int64
	Useragent string
	Lastvisit int64
}

type Stat struct {
	Dateline   int64
	Numusers   int64
	Numthreads int64
	Numposts   int64
}

type Task struct {
	Tid         int64
	Title       string
	Description string
	File        string
	Minute      string
	Hour        string
	Day         string
	Month       string
	Weekday     string
	Nextrun     int64
	Lastrun     int64
	Enabled     int64
	Logging     int64
	Locked      int64
}

type Tasklog struct {
	Lid      int64
	Tid      int64
	Dateline int64
	Data     string
}

type Template struct {
	Tid      int64
	Title    string
	Template string
	Sid      int64
	Version  string
	Status   string
	Dateline int64
}

type Templategroup struct {
	Gid       int64
	Prefix    string
	Title     string
	Isdefault int64
}

type Templateset struct {
	Sid   int64
	Title string
}

type Theme struct {
	Tid           int64
	Name          string
	Pid           int64
	Def           int64
	Properties    string
	Stylesheets   string
	Allowedgroups string
}

type Themestylesheet struct {
	Sid          int64
	Name         string
	Tid          int64
	Attachedto   string
	Stylesheet   string
	Cachefile    string
	Lastmodified int64
}

type Thread struct {
	Tid             int64
	Fid             int64
	Subject         string
	Prefix          int64
	Icon            int64
	Poll            int64
	Uid             int64
	Username        string
	Dateline        int64
	Firstpost       int64
	Lastpost        int64
	Lastposter      string
	Lastposteruid   int64
	Views           int64
	Replies         int64
	Closed          string
	Sticky          int64
	Numratings      int64
	Totalratings    int64
	Notes           string
	Visible         int8
	Unapprovedposts int64
	Deletedposts    int64
	Attachmentcount int64
	Deletetime      int64
}

type Threadprefix struct {
	Pid          int64
	Prefix       string
	Displaystyle string
	Forums       string
	Groups       string
}

type Threadrating struct {
	Rid       int64
	Tid       int64
	Uid       int64
	Rating    int64
	Ipaddress string
}

type Threadsread struct {
	Tid      int64
	Uid      int64
	Dateline int64
}

type Threadsubscription struct {
	Sid          int64
	Uid          int64
	Tid          int64
	Notification int64
	Dateline     int64
}

type Threadview struct {
	Tid int64
}

type UpgradeDatum struct {
	Title    string
	Contents string
}

type User struct {
	Uid                int64
	Username           string
	Password           string
	Salt               string
	Loginkey           string
	Email              string
	Postnum            int64
	Threadnum          int64
	Avatar             string
	Avatardimensions   string
	Avatartype         string
	Usergroup          int64
	Additionalgroups   string
	Displaygroup       int64
	Usertitle          string
	Regdate            int64
	Lastactive         int64
	Lastvisit          int64
	Lastpost           int64
	Website            string
	Icq                string
	Skype              string
	Google             string
	Birthday           string
	Birthdayprivacy    string
	Signature          string
	Allownotices       int64
	Hideemail          int64
	Subscriptionmethod int64
	Invisible          int64
	Receivepms         int64
	Receivefrombuddy   int64
	Pmnotice           int64
	Pmnotify           int64
	Buddyrequestspm    int64
	Buddyrequestsauto  int64
	Threadmode         string
	Showimages         int64
	Showvideos         int64
	Showsigs           int64
	Showavatars        int64
	Showquickreply     int64
	Showredirect       int64
	Ppp                int64
	Tpp                int64
	Daysprune          int64
	Dateformat         string
	Timeformat         string
	Timezone           string
	Dst                int64
	Dstcorrection      int64
	Buddylist          string
	Ignorelist         string
	Style              int64
	Away               int64
	Awaydate           int64
	Returndate         string
	Awayreason         string
	Pmfolders          string
	Notepad            string
	Referrer           int64
	Referrals          int64
	Reputation         int64
	Regip              string
	Lastip             string
	Language           string
	Timeonline         int64
	Showcodebuttons    int64
	Totalpms           int64
	Unreadpms          int64
	Warningpoints      int64
	Moderateposts      int64
	Moderationtime     int64
	Suspendposting     int64
	Suspensiontime     int64
	Suspendsignature   int64
	Suspendsigtime     int64
	Coppauser          int64
	Classicpostbit     int64
	Loginattempts      int64
	Usernotes          string
	Sourceeditor       int64
	Loginlockoutexpiry int64
}

type Userfield struct {
	Ufid int64
	Fid1 string
	Fid2 string
	Fid3 string
}

type Usergroup struct {
	Gid                      int64
	Type                     int64
	Title                    string
	Description              string
	Namestyle                string
	Usertitle                string
	Stars                    int64
	Starimage                string
	Image                    string
	Disporder                int64
	Isbannedgroup            int64
	Canview                  int64
	Canviewthreads           int64
	Canviewprofiles          int64
	Candlattachments         int64
	Canviewboardclosed       int64
	Canpostthreads           int64
	Canpostreplys            int64
	Canpostattachments       int64
	Canratethreads           int64
	Modposts                 int64
	Modthreads               int64
	ModEditPosts             int64
	Modattachments           int64
	Caneditposts             int64
	Candeleteposts           int64
	Candeletethreads         int64
	Caneditattachments       int64
	Canviewdeletionnotice    int64
	Canpostpolls             int64
	Canvotepolls             int64
	Canundovotes             int64
	Canusepms                int64
	Cansendpms               int64
	Cantrackpms              int64
	Candenypmreceipts        int64
	Pmquota                  int64
	Maxpmrecipients          int64
	Cansendemail             int64
	Cansendemailoverride     int64
	Maxemails                int64
	Emailfloodtime           int64
	Canviewmemberlist        int64
	Canviewcalendar          int64
	Canaddevents             int64
	Canbypasseventmod        int64
	Canmoderateevents        int64
	Canviewonline            int64
	Canviewwolinvis          int64
	Canviewonlineips         int64
	Cancp                    int64
	Issupermod               int64
	Cansearch                int64
	Canusercp                int64
	Canbeinvisible           int64
	Canuploadavatars         int64
	Canratemembers           int64
	Canchangename            int64
	Canbereported            int64
	Canchangewebsite         int64
	Showforumteam            int64
	Usereputationsystem      int64
	Cangivereputations       int64
	Candeletereputations     int64
	Reputationpower          int64
	Maxreputationsday        int64
	Maxreputationsperuser    int64
	Maxreputationsperthread  int64
	Candisplaygroup          int64
	Attachquota              int64
	Cancustomtitle           int64
	Canwarnusers             int64
	Canreceivewarnings       int64
	Maxwarningsday           int64
	Canmodcp                 int64
	Showinbirthdaylist       int64
	Canoverridepm            int64
	Canusesig                int64
	Canusesigxposts          int64
	Signofollow              int64
	Edittimelimit            int64
	Maxposts                 int64
	Showmemberlist           int64
	Canmanageannounce        int64
	Canmanagemodqueue        int64
	Canmanagereportedcontent int64
	Canviewmodlogs           int64
	Caneditprofiles          int64
	Canbanusers              int64
	Canviewwarnlogs          int64
	Canuseipsearch           int64
}

type Usertitle struct {
	Utid      int64
	Posts     int64
	Title     string
	Stars     int64
	Starimage string
}

type Warning struct {
	Wid          int64
	Uid          int64
	Tid          int64
	Pid          int64
	Title        string
	Points       int64
	Dateline     int64
	Issuedby     int64
	Expires      int64
	Expired      int64
	Daterevoked  int64
	Revokedby    int64
	Revokereason string
	Notes        string
}

type Warninglevel struct {
	Lid        int64
	Percentage int64
	Action     string
}

type Warningtype struct {
	Tid            int64
	Title          string
	Points         int64
	Expirationtime int64
}
