// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: posts.sql

package mybb

import (
	"context"
)

const fetchPosts = `-- name: FetchPosts :many
SELECT pid,
       username,
       dateline,
       subject,
       replyto,
       message
FROM posts
WHERE tid=?
ORDER BY dateline
`

type FetchPostsRow struct {
	Pid      int64
	Username string
	Dateline int64
	Subject  string
	Replyto  int64
	Message  string
}

func (q *Queries) FetchPosts(ctx context.Context, tid int64) ([]FetchPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, fetchPosts, tid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchPostsRow
	for rows.Next() {
		var i FetchPostsRow
		if err := rows.Scan(
			&i.Pid,
			&i.Username,
			&i.Dateline,
			&i.Subject,
			&i.Replyto,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
