// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: site.sql

package mybb

import (
	"context"
)

const getTitleCache = `-- name: GetTitleCache :one
SELECT title, cache
FROM datacache
`

func (q *Queries) GetTitleCache(ctx context.Context) (Datacache, error) {
	row := q.db.QueryRowContext(ctx, getTitleCache)
	var i Datacache
	err := row.Scan(&i.Title, &i.Cache)
	return i, err
}
